### ISSUE TITLE
rev1 assembler errors

### ISSUE THREAD

**Issue by Hendi48** [SnowyMouse/fancy-mouse-boot-rom#1]
I'm getting this output with GCC 8.3.0 on Debian Buster:
```
mouse.S: Assembler messages:
mouse.S:353: Warning: `dword ptr [esi]' is not valid here (expected `[edi]')
mouse.S:353: Warning: `dword ptr [edi]' is not valid here (expected `[esi]')
mouse.S:353: Error: invalid instruction suffix for `cmpsd'
make: *** [Makefile:19: bin/mouse_rev1.bin] Error 1
```

Specifying operands for `cmpsd` appears to be superfluous, since it always compares `[esi]` and `[edi]` regardless of what one specifies. With `repe cmpsd` it assembles fine, but I haven't tested it.

**Comment by SnowyMouse** [comment]
Fixed in 40662a8d33ffa09f1dc428125b5aca0227fdcd8f
